### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Andrey1008** [Quart-Addons/quart-uploads#2]
If file size is 5mb or more uploading file often returns ERR_HTTP2_PROTOCOL_ERROR after 20 seconds of loading. This also happens with files of lower size, but not so often.

**Comment by crood58** [comment]
What version of Python are you using?

**Comment by crood58** [comment]
This being closed, since it old and I could not reproduce the error. Also, the original author never responded to responses regarding this issue. 

We can reopen in the future if needed.
